const { GoogleGenerativeAI } = require('@google/generative-ai');
const puppeteer = require('puppeteer')


const ai = new GoogleGenerativeAI(process.env.GOOGLE_GENAI_API_KEY)

async function invokeGeminiAi() {
    const response = await ai.getGenerativeModel({ model: "gemini-2.5-flash" }).generateContent("Hello gemini ! Exxplain what is Interview ?")

    console.log(response.response.text())
}


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `Genrate an interview report for an candidate with the following details:
    Resume: ${resume}
    Self Description: ${selfDescription}
    Job Description: ${jobDescription}
    
    The report should include a match score, technical and behavioral questions, skill gaps, and a preparation plan.`

    const schema = {
        type: "object",
        properties: {
            matchScore: { type: "integer", description: "A score between 0 and 100" },
            technicalQuestions: {
                type: "array",
                items: {
                    type: "object",
                    properties: {
                        question: { type: "string" },
                        intention: { type: "string" },
                        answer: { type: "string" }
                    },
                    required: ["question", "intention", "answer"]
                }
            },
            behavioralQuestions: {
                type: "array",
                items: {
                    type: "object",
                    properties: {
                        question: { type: "string" },
                        intention: { type: "string" },
                        answer: { type: "string" }
                    },
                    required: ["question", "intention", "answer"]
                }
            },
            skillGaps: {
                type: "array",
                items: {
                    type: "object",
                    properties: {
                        skill: { type: "string" },
                        severity: { type: "string", enum: ["low", "medium", "high"] }
                    },
                    required: ["skill", "severity"]
                }
            },
            preparationPlan: {
                type: "array",
                items: {
                    type: "object",
                    properties: {
                        day: { type: "integer" },
                        focus: { type: "string" },
                        tasks: { type: "array", items: { type: "string" } }
                    },
                    required: ["day", "focus", "tasks"]
                }
            },
            title: { type: "string" }
        },
        required: ["matchScore", "technicalQuestions", "behavioralQuestions", "skillGaps", "preparationPlan", "title"]
    }

    const model = ai.getGenerativeModel({
        model: "gemini-2.5-flash",
        generationConfig: {
            responseMimeType: "application/json",
            responseSchema: schema,
        }
    })

    const response = await model.generateContent(prompt)

    return (JSON.parse(response.response.text()))
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setContent(htmlContent, {waituntil: "networkidle0"})

    const pdfBuffer =await page.pdf({ format: "A4", margin:{
        top: "20mm",
        bottom: "20mm",
        left: "15mm",
        right: "15mm",
    }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({resume, selfDescription, jobDescription}) {


const prompt = `Generate a resume foa a candidate with the foollowing details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library.
The resume should be tailored for the given job description and should highlight the candidate's strengths and relevent experience. The HTML content should be well-formatted and structed, making it easy to read and visible.
The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume. 
you can highlight the content using some colors or ddifferent font styles but the overall design should be simple and professional.
The content should be ATS friendly, i.e. should be easily parsable by ATS system without losing important information. 
The resume should not be so lenghty, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.`

    const schema = {
        type: "object",
        properties: {
            html: { type: "string", description: "The HTML content of the resume" }
        },
        required: ["html"]
    }

    const model = ai.getGenerativeModel({
        model: "gemini-2.5-flash",
        generationConfig: {
            responseMimeType: "application/json",
            responseSchema: schema
        }
    })

    const response = await model.generateContent(prompt)

    const jsonContent = JSON.parse(response.response.text())

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

  return pdfBuffer

}

module.exports = { generateInterviewReport, invokeGeminiAi, generateResumePdf };